modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "noisemakerdetector"
version = "${version}"
displayName = "Noisemaker Detector"
authors = "PrecPrecise"
description = '''
Detects and highlights noise-making blocks connected to redstone circuitry with ESP outlines and beacon beams.
'''

[[dependencies.noisemakerdetector]]
modId = "neoforge"
type = "required"
versionRange = "[21.11,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.noisemakerdetector]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "CLIENT"
